let humanScore;
let computerScore;
let round;

const buttonContainer = document.querySelector(".button-container");
const winnerHeading = document.querySelector("#winner");
const roundWinnerHeading = document.querySelector("#round-winner");
const hScore = document.querySelector("#human-score");
const cScore = document.querySelector("#computer-score");
const rNumber = document.querySelector("#round-number");

// Added to set variables when page loads
document.addEventListener("onload", start());

// Added to reset the variables 
function start() {
    humanScore = 0;
    computerScore = 0;
    round = 0;
    buttonContainer.hidden = false;
    winnerHeading.textContent = "";
    roundWinnerHeading.textContent = "";
    updateScore();
    updateRound();
}

// Function that gives rock, paper or scissor based on random number out of 1, 2 and 3 generated by Math.random() and a little formula
function getComputerChoice() {
    let choice = Math.floor(Math.random() * 3) + 1;

    if (choice == 1) {
        return "rock";
    } else if (choice == 2) {
        return "paper";
    } else {
        return "scissors";
    }
}

// Function that asks user to enter rock, paper or scissor which is converted to lowercase for simplicity
function getHumanChoice(event) {
    let choice = event.target.id;
    return choice.toLocaleLowerCase();
}

// Updates the html document score with the variable score in js
function updateScore() {
    hScore.textContent = humanScore;
    cScore.textContent = computerScore;
}

// Updates the round number with round variable value in js
function updateRound() {
    rNumber.textContent = round;
}

// Updates the winner of round
function updateRoundWinner(winner) {
    if(winner === "human") {
        roundWinnerHeading.textContent = "You win this round!";
    } else if (winner === "computer") {
        roundWinnerHeading.textContent = "Computer wins this round!";
    } else {
        roundWinnerHeading.textContent = "Draw!";
    }
}

// Function that returns and logs winner of a round of rock, paper and scissors
function playRound(humanChoice, computerChoice) {
    if ((humanChoice == "rock" && computerChoice == "scissors") || (humanChoice == "paper" && computerChoice == "rock") || (humanChoice == "scissors" && computerChoice == "paper")) {
        humanScore++;
        console.log("Player Wins!");
        return "human";
    } else if (computerChoice == humanChoice) {
        console.log("Draw!");
        return "Draw";
    } else {
        computerScore++;
        console.log("Computer Wins!");
        return "computer"
    }
}

// Function that declares the winner when either comoputer or player wins
function declareWinner(winner) {
    winnerHeading.textContent = winner === "human" ? "You win the game!" : "You lost the game!";
    buttonContainer.hidden = true;
}

// Function what checks if anyone won
function checkWinner() {
    if (humanScore === 5) {
        declareWinner("human");
        console.log("Player wins the game!");
    } else if (computerScore === 5) {
        declareWinner("computer");
        console.log("Computer wins the game!");
    }
}

// Function that plays entire game by calling playGame() function 5 times using for loop and then alters and logs result
function playGame(event) {
    let humanChoice = getHumanChoice(event);
    let computerChoice = getComputerChoice();

    let result = playRound(humanChoice, computerChoice);
    round++;

    updateScore();
    updateRound();
    updateRoundWinner(result);
    console.log(`You chose: ${humanChoice}\nComputer chose: ${computerChoice}\n${result}\nYour Score: ${humanScore}\nComputer Score: ${computerScore}`);
    checkWinner();
}

// playGame();
buttonContainer.addEventListener("click", (event) => {
    playGame(event);
});

const restart = document.querySelector("#restart");
restart.addEventListener("click", start);