// Variables that store score 
let humanScore = 0;
let computerScore = 0;

// Function that gives rock, paper or scissor based on random number out of 1, 2 and 3 generated by Math.random() and a little formula
function getComputerChoice() {
    let choice = Math.floor(Math.random() * 3) + 1;

    if (choice == 1) {
        return 'rock';
    } else if (choice == 2) {
        return 'paper';
    } else {
        return 'scissors';
    }
}

// Function that asks user to enter rock, paper or scissor which is converted to lowercase for simplicity
function getHumanChoice() {
    let choice = prompt('Choose Rock, Paper or Scissors...\n');
    return choice.toLocaleLowerCase();
}

// Function that returns and logs winner of a round of rock, paper and scissors
function playRound(humanChoice, computerChoice) {
    if ((humanChoice == 'rock' && computerChoice == 'scissors') || (humanChoice == 'paper' && computerChoice == 'rock') || (humanChoice == 'scissors' && computerChoice == 'paper')) {
        humanScore++;
        console.log('You win!');
        return 'You win!';
    } else if (computerChoice == humanChoice) {
        console.log('Draw!');
        return 'Draw';
    } else {
        computerScore++;
        console.log('You lost!');
        return 'You lose!'
    }
}

// Function that plays entire game by calling playGame() function 5 times using for loop and then alters and logs result
function playGame() {
    for (let i = 0; i < 5; i++) {
        console.log(`Round ${i + 1}`);
        let humanChoice = getHumanChoice();
        let computerChoice = getComputerChoice();
        let winner = playRound(humanChoice, computerChoice);

        console.log(`Round ${i + 1}\nYou chose: ${humanChoice}\nComputer chose: ${computerChoice}\n${winner}`);
        alert(`Round ${i + 1}\nYou chose: ${humanChoice}\nComputer chose: ${computerChoice}\n${winner}`);
    }

    if (humanScore > computerScore) {
        alert(`You win the game!\nYour Score: ${humanScore}\nComputer Score: ${computerScore}`);
        console.log('You win the game!');
    } else if (computerScore > humanScore) {
        alert(`You lost the game! Computer wins!\nYour Score: ${humanScore}\nComputer Score: ${computerScore}`);
        console.log('You lost the game!');
    } else {
        alert(`Draw!\nYour Score: ${humanScore}\nComputer Score: ${computerScore}`);
        console.log('Draw!');
    }

    console.log(`Your Score: ${humanScore}\nComputer Score: ${computerScore}`);
}

// playGame();
const buttonContainer = document.querySelector(".button-container");
buttonContainer.addEventListener("click", (event) => {
    let humanChoice = event.target.id;
    let computerChoice = getComputerChoice();
    let result = playRound(humanChoice, computerChoice);
    console.log(`You chose: ${humanChoice}\nComputer chose: ${computerChoice}\n${result}\nYour Score: ${humanScore}\nComputer Score: ${computerScore}`);
});